# Generated by Django 3.2.3 on 2021-05-22 14:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ResumeData', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='end_date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 5, 22, 14, 2, 21, 212259, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='experience',
            name='starting_date',
            field=models.DateField(default=datetime.datetime(2021, 5, 22, 14, 2, 21, 212231, tzinfo=utc)),
        ),
    ]
