# Generated by Django 3.2.3 on 2021-05-22 14:26

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ResumeData', '0002_auto_20210522_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='end_date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 5, 22, 14, 26, 57, 834088, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='experience',
            name='starting_date',
            field=models.DateField(default=datetime.datetime(2021, 5, 22, 14, 26, 57, 834064, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='CareerObjective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objective', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
